// benchmarks/apps/solid/src/App.js
import { escape, ssr } from 'solid-js/web';
import { createData } from '../../../data';

export const App = () =>
  ssr(
    ['<div>', '</div>'],
    createData().map((item) =>
      ssr(
        ['<div><h3>', '</h3><p>', '</p></div>'],
        escape(item.name),
        escape(item.value),
      ),
    ),
  );

// benchmarks/apps/qwik/src/App.tsx
/** @jsxImportSource @builder.io/qwik */
import { component$ } from '@builder.io/qwik'
import { createData } from '../../../data'

export const App = component$(() => (
  <div>
    {createData().map((item) => (
      <div key={item.id}>
        <h3>{item.name}</h3>
        <p>{item.value}</p>
      </div>
    ))}
  </div>
))
